apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odoo.fullname" $ }}-config
  labels:
    {{- include "odoo.labels" $ | nindent 4 }}
data:
  odoo.conf: |
    {{- tpl .Values.config . | nindent 4 }}
