apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo.fullname" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.ports.websocket }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "odoo.selectorLabels" . | nindent 4 }}
