{{- if and .Values.machineLearning.enabled .Values.machineLearning.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "immich.fullname" . }}-machine-learning
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: machine-learning
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "immich.fullname" . }}-machine-learning
  minReplicas: {{ .Values.machineLearning.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.machineLearning.autoscaling.maxReplicas }}
  {{- with .Values.machineLearning.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
    {{- if .Values.machineLearning.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.machineLearning.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.machineLearning.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.machineLearning.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
