{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich.fullname" . }}-media
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: media
  {{- if or .Values.persistence.media.keep .Values.persistence.media.annotations }}
  annotations:
    {{- if .Values.persistence.media.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.persistence.media.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.media.accessModes }}
    - {{ . }}
    {{- end }}
  {{- with .Values.persistence.media.storageClass }}
  {{- if eq "-" . }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ . | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
{{- end }}
