{{- if .Values.postgres.password.value }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "immich.databaseCredentialName" . }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
stringData:
  password: {{ .Values.postgres.password.value | quote }}
  {{- if .Values.postgres.enabled }}
  username: {{ include "immich.databaseUser" . | quote }}
  {{- end }}
{{- end }}
{{- if .Values.redis.password.value }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "immich.redisPasswordName" . }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
stringData:
  password: {{ .Values.redis.password.value | quote }}
{{- end }}
{{- if .Values.jwtSecret.value }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "immich.jwtSecretName" . }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
stringData:
  jwt-secret: {{ .Values.jwtSecret.value | quote }}
{{- end }}
