{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitors.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "immich.fullname" . }}
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- with .Values.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: app.kubernetes.io/component
  {{- with .Values.monitoring.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "immich.labels" . | nindent 6 }}
      app.kubernetes.io/component: server
  endpoints:
    - port: metrics-api
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
      honorLabels: {{ .Values.monitoring.honorLabels }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "immich.fullname" . }}-microservices
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: microservices
    {{- with .Values.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.monitoring.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: app.kubernetes.io/component
  {{- with .Values.monitoring.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "immich.labels" . | nindent 6 }}
      app.kubernetes.io/component: microservices
  endpoints:
    - port: metrics-ms
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
      honorLabels: {{ .Values.monitoring.honorLabels }}
{{- end }}
