secretName: postgres-secret
createSecret: false

extraManifests:
  - |
    kind: Secret
    apiVersion: v1
    metadata:
      name: postgres-secret
    stringData:
      username: my-user
      password: my-password
