secret:
  create: false
  name: postgres-secret

extraManifests:
  - |
    kind: Secret
    apiVersion: v1
    metadata:
      name: postgres-secret
    stringData:
      username: my-user
      password: my-password
