apiVersion: v2
name: paperless-ngx
description: A Helm chart for Kubernetes
type: application
version: 0.3.4
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: "3.1.0"
maintainers:
  - name: walnuss0815
    email: walnuss0815@gmail.com
    url: https://github.com/walnuss0815

dependencies:
  - name: valkey
    version: "0.11.0"
    repository: https://valkey.io/valkey-helm/
    condition: valkey.enabled
  - name: webdav
    version: "0.1.11"
    repository: https://walnuss0815.github.io/helm-charts
    condition: webdav.enabled
  - name: tika
    version: "0.1.3"
    repository: https://walnuss0815.github.io/helm-charts
    condition: tika.enabled
  - name: gotenberg
    version: "0.1.7"
    repository: https://walnuss0815.github.io/helm-charts
    condition: gotenberg.enabled
