
{{- if .Values.createSecret }}
{{- $password := randAlphaNum 32 }}
{{- $postgresPassword := randAlphaNum 32 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  host: {{ (include "postgres.fullname" .) | b64enc | quote }}
  port: {{ .Values.port | toString | b64enc | quote }}
  database: {{ (tpl .Values.database .) | b64enc | quote }}
  username: {{ (tpl .Values.username .) | b64enc | quote }}
  password: {{ $password | b64enc | quote }}
  postgres-password: {{ $password | b64enc | quote }}
  uri: {{ (printf "postgresql://%s:%s@%s:%s/%s" (tpl .Values.username .) $password (include "postgres.fullname" .) .Values.port .Values.database) | b64enc | quote }}
{{- end }}
