user:
  username:
    secretKeyRef:
      name: "webdav-creds"
      key: "username"
  password:
    secretKeyRef:
      name: "webdav-creds"
      key: "password"

extraManifests:
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: "webdav-creds"
    stringData:
      username: "my-user"
      password: "my-password"
