apiVersion: v2
name: openchamber
description: A Helm chart for OpenChamber, a web workspace for running and reviewing AI coding work with OpenCode
type: application
version: 0.1.0
# renovate: image=ghcr.io/coyotle/openchamber
appVersion: "v2.2.0"
home: https://openchamber.dev
sources:
  - https://github.com/openchamber/openchamber
  - https://github.com/coyotle/openchamber
maintainers:
  - name: walnuss0815
    email: walnuss0815@gmail.com
    url: https://github.com/walnuss0815
