apiVersion: v2
name: gotenberg
description: A Helm chart for Kubernetes
type: application
version: 0.1.4
appVersion: "8.23"
maintainers:
  - name: walnuss0815
    email: walnuss0815@gmail.com
    url: https://github.com/walnuss0815
