apiVersion: v2
name: kavita
description: A Helm chart for Kavita
type: application
version: 0.1.1
appVersion: "0.8.9"
maintainers:
  - name: walnuss0815
    email: walnuss0815@gmail.com
    url: https://github.com/walnuss0815
