apiVersion: v2
name: linkwarden
description: A Helm chart for Linkwarden
type: application
version: 0.1.0
# renovate: image=ghcr.io/linkwarden/linkwarden
appVersion: "2.13.1"
maintainers:
  - name: walnuss0815
    email: walnuss0815@gmail.com
    url: https://github.com/walnuss0815
