apiVersion: v2
name: handbrake-web
description: A Helm chart for HandBrake Web
type: application
version: 0.1.1
# renovate: image=ghcr.io/thenickoftime/handbrake-web-server
appVersion: "0.8.1"
maintainers:
  - name: walnuss0815
    email: walnuss0815@gmail.com
    url: https://github.com/walnuss0815

dependencies:
  - name: webdav
    version: "0.1.12"
    repository: https://walnuss0815.github.io/helm-charts
    condition: webdav.enabled
