{{- if and .Values.policy.enabled (not .Values.policy.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openchamber.fullname" . }}-policy
  labels:
    {{- include "openchamber.labels" . | nindent 4 }}
type: Opaque
data:
  policy.json: {{ toPrettyJson .Values.policy.content | b64enc | quote }}
{{- end }}
