apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "immich-kiosk.fullname" $ }}-config
  labels:
    {{- include "immich-kiosk.labels" $ | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (toYaml .Values.config) . | nindent 4 }}
