apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "immich-kiosk.fullname" $ }}-custom-css
  labels:
    {{- include "immich-kiosk.labels" $ | nindent 4 }}
data:
  custom.css: |
    {{- tpl .Values.customCSS . | nindent 4 }}
