{{- if .Values.immich.apiKey.value }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "immich-kiosk.fullname" $ }}-immich-api-key
  labels:
    {{- include "immich-kiosk.labels" $ | nindent 4 }}
stringData:
  immich-api-key: {{ .Values.immich.apiKey.value | quote }}
---
{{- end }}

{{- if .Values.password.value }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "immich-kiosk.fullname" $ }}-password
  labels:
    {{- include "immich-kiosk.labels" $ | nindent 4 }}
stringData:
  password: {{ .Values.password.value | quote }}
---
{{- end }}

{{- if .Values.weather.apiKey.value }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "immich-kiosk.fullname" $ }}-weather-api-key
  labels:
    {{- include "immich-kiosk.labels" $ | nindent 4 }}
stringData:
  weather-api-key: {{ .Values.weather.apiKey.value | quote }}
---
{{- end }}
