nextauth:
  secret:
    secretKeyRef:
      name: "linkwarden-secrets"
      key: "nextauth-secret"

extraManifests:
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: "linkwarden-secrets"
    stringData:
      nextauth-secret: "ci-test-secret"
