apiVersion: v2
name: postgres
description: A Helm chart for PostgreSQL
type: application
version: 0.3.0
appVersion: "18.3"
maintainers:
  - name: walnuss0815
    email: walnuss0815@gmail.com
    url: https://github.com/walnuss0815
