apiVersion: v2
name: chisel
description: A Helm chart for Chisel
type: application
version: 0.1.4
# renovate: image=jpillora/chisel
appVersion: "1.12.0"
maintainers:
  - name: walnuss0815
    email: walnuss0815@gmail.com
    url: https://github.com/walnuss0815
