immich:
  url: "http://immich.example.com"
  apiKey:
    secretKeyRef:
      name: external-immich-api-key
      key: api-key
password:
  secretKeyRef:
    name: external-kiosk-password
    key: pwd
weather:
  apiKey:
    secretKeyRef:
      name: external-weather-key
      key: openweather
config:
  weather:
    locations:
      - name: london
        lat: 51.5285262
        lon: -0.2663999
        api: ""
        unit: metric
        lang: en
extraManifests:
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-immich-api-key
    type: Opaque
    stringData:
      api-key: immich-test-key
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-kiosk-password
    type: Opaque
    stringData:
      pwd: kiosk-test-password
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: external-weather-key
    type: Opaque
    stringData:
      openweather: weather-test-key
