immich:
  url: "http://immich.example.com"
  apiKey:
    value: "immich-test-key"
password:
  value: "kiosk-test-password"
weather:
  apiKey:
    value: "weather-test-key"
config:
  weather:
    locations:
      - name: london
        lat: 51.5285262
        lon: -0.2663999
        api: ""
        unit: metric
        lang: en
