kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "linkwarden.fullname" $ }}-data
  labels:
    {{- include "linkwarden.labels" $ | nindent 4 }}
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- if not (empty .Values.persistence.data.accessModes) }}
  {{- range .Values.persistence.data.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.persistence.data.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- if not (eq .Values.persistence.data.storageClass "-") }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
