name: Lint and Test Charts

on: pull_request

permissions: {}

jobs:
  list-changed:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changed-charts: ${{ steps.list-changed.outputs.changed-charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml --target-branch ${{ github.event.repository.default_branch }})
          charts_json=$(echo "$changed" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "changed-charts=$charts_json" >> "$GITHUB_OUTPUT"

  lint-test:
    needs: list-changed
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        chart: ${{ fromJson(needs.list-changed.outputs.changed-charts) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --target-branch ${{ github.event.repository.default_branch }} --charts ${{ matrix.chart }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.14.0

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml --target-branch ${{ github.event.repository.default_branch }} --charts ${{ matrix.chart }}
